### PR TITLE
Ere 148

### PR DESCRIPTION
**Pull request by barelyThinkingBagOfWater**
As requested in the comments of the Jira task the .env file as been removed and env variables are set up in the workflow configuration files.
I did some tests to use Windows as the build OS in the workflow but it causes problems with the DocumentService when it creates some xml files in the temporary directory (like in line 195).

### CODE REVIEW

**Comment by cartel1** [comment]
@barelyThinkingBagOfWater Thanks. It would be good to have this running on Windows which is the target environment for the upcoming release. What is the specific problem being experienced with the DocumentService? @OmarMalass is using Windows. I've asked him to check if he is experiencing problems as well assuming it's not an OS version issue.

**Comment by barelyThinkingBagOfWater** [comment]
You can find  the stacktraces here : https://github.com/ere-health/ere-ps-app/runs/2781881805?check_suite_focus=true
Here is the one : 
2021-06-09 08:45:53,009 SEVERE [hea.ere.ps.ser.pdf.DocumentService] (main) Could not generate ERezept PDF: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: file:/C:/Users/RUNNER~1/AppData/Local/Temp/bundle-1845152425606715324.xml; lineNumber: 5; columnNumber: 2134; Invalid byte 1 of 1-byte UTF-8 sequence.

Now I'm not familiar with this service yet and I haven't really dug into this error but from what I understand there is a problem with the writing of these temporary files. It might be specific to this windows vm so still works on Omar's computer. 
I'll start working tomorrow on the task ERE-300/301 that I think are linked to this part of the code. I'll take a deeper look at this problem then.

**Comment by OmarMalass** [comment]
I got the same error.

**Comment by cartel1** [comment]
@barelyThinkingBagOfWater @OmarMalass Thanks for the confirmation.  We need to look at this issue further as this initial release is primarily targeted for Windows.

**Comment by barelyThinkingBagOfWater** [comment]
I'm not sure where to post this but the relevant people are following these comments so : the bug is fixed. You just have to force the use of UTF-8 when saving the temporary file like this:
Files.write(tmpFile.toPath(), serialized.getBytes(StandardCharsets.UTF_8));
Tested on the Windows build OS with Github Actions.

**Comment by ManuelB** [comment]
@barelyThinkingBagOfWater good job!

**Pull request merged**
